sudo: required
services:
  -docker

before_install:
  - docker build -t jnmorse/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jnmorse/react-test npm test -- --coverage

after_success:
  - docker build -t jnmorse/multi-client ./client
  - docker build -t jnmorse/multi-nginx ./nginx
  - docker build -t jnmorse/multi-server ./server
  - docker build -t jnmorse/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push jnmorse/multi-client
  - docker push jnmorse/multi-nginx
  - docker push jnmorse/multi-server
  - docker push jnmorse/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Multi-Docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-573537116965
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
